# Generated by Django 5.2.17 on 2026-09-19 11:00

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImmutablePostedJournalEntry',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=1024)),
                ('transaction_currency_code', models.CharField(max_length=10)),
                ('is_posted', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounting_immutable_posted_journal_entry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImmutablePostedJournalLine',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('memo', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounting_immutable_posted_journal_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('account_type', models.CharField(choices=[('BANK', 'Bank'), ('CASH', 'Cash'), ('CREDIT', 'Credit Card'), ('ASSET', 'Asset'), ('RECEIVABLE', 'Accounts Receivable'), ('STOCK', 'Stock'), ('MUTUAL', 'Mutual Fund'), ('CURRENCY', 'Currency'), ('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('MONEYMRKT', 'Money Market'), ('LIABILITY', 'Liability'), ('PAYABLE', 'Accounts Payable'), ('CREDITLINE', 'Credit Line'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('EQUITY', 'Equity'), ('ROOT', 'Root Account'), ('TRADING', 'Trading')], max_length=20)),
                ('is_placeholder', models.BooleanField(default=False)),
                ('is_system_account', models.BooleanField(default=False, help_text='System account (hidden from users, e.g., trading accounts for multi-currency)')),
                ('path', models.CharField(blank=True, max_length=1000)),
                ('level', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('JOURNAL_CREATED', 'Journal Entry Created'), ('JOURNAL_POSTED', 'Journal Entry Posted'), ('JOURNAL_REVERSED', 'Journal Entry Reversed'), ('JOURNAL_CORRECTED', 'Journal Entry Corrected'), ('JOURNAL_VOIDED', 'Journal Entry Voided'), ('ACCOUNT_CREATED', 'Account Created'), ('ACCOUNT_MODIFIED', 'Account Modified'), ('ACCOUNT_DELETED', 'Account Deleted'), ('RECONCILE_STATUS_CHANGED', 'Reconciliation Status Changed'), ('RECONCILIATION_STARTED', 'Bank Reconciliation Started'), ('RECONCILIATION_COMPLETED', 'Bank Reconciliation Completed'), ('PERIOD_CLOSED', 'Fiscal Period Closed'), ('PERIOD_LOCKED', 'Fiscal Period Locked'), ('PERIOD_REOPENED', 'Fiscal Period Reopened'), ('INTERCOMPANY_PROPOSED', 'Intercompany Event Proposed'), ('INTERCOMPANY_ACCEPTED', 'Intercompany Event Accepted'), ('INTERCOMPANY_REJECTED', 'Intercompany Event Rejected'), ('DOCUMENT_POSTED', 'Document Posted'), ('DOCUMENT_REVERSED', 'Document Reversed')], db_index=True, max_length=50)),
                ('entity_type', models.CharField(db_index=True, max_length=50)),
                ('entity_id', models.CharField(db_index=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('routing_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_balance', models.DecimalField(decimal_places=10, max_digits=20)),
                ('ledger_balance', models.DecimalField(decimal_places=10, max_digits=20)),
                ('difference', models.DecimalField(decimal_places=10, max_digits=20)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=10, max_digits=20)),
                ('closing_balance', models.DecimalField(decimal_places=10, max_digits=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('source', models.CharField(max_length=50)),
                ('raw_file_key', models.CharField(blank=True, max_length=500)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('description', models.CharField(max_length=1024)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('online_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('match_status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('SUGGESTED', 'Suggested'), ('MATCHED', 'Matched'), ('EXCLUDED', 'Excluded')], db_index=True, default='UNMATCHED', max_length=20)),
                ('match_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('namespace', models.CharField(choices=[('CURRENCY', 'Currency'), ('SECURITY', 'Security'), ('CRYPTO', 'Cryptocurrency')], max_length=20)),
                ('mnemonic', models.CharField(db_index=True, max_length=10)),
                ('fullname', models.CharField(max_length=255)),
                ('cusip', models.CharField(blank=True, max_length=20, null=True)),
                ('fraction', models.IntegerField(default=100)),
                ('quote_flag', models.BooleanField(default=False)),
                ('quote_source', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterpartPosting',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_date', models.DateField(db_index=True)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rate_date'],
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('locked', 'Locked')], db_index=True, default='open', max_length=20)),
                ('fiscal_year', models.IntegerField(db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='IntercompanyRelationship',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('PARENT_SUBSIDIARY', 'Parent-Subsidiary'), ('SISTER_COMPANIES', 'Sister Companies'), ('AFFILIATED', 'Affiliated')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterEntityEvent',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('ACCEPTED', 'Accepted'), ('MODIFIED', 'Modified'), ('REJECTED', 'Rejected')], db_index=True, default='PROPOSED', max_length=20)),
                ('mismatch_status', models.CharField(choices=[('MATCHED', 'Matched'), ('AMOUNT_MISMATCH', 'Amount Mismatch'), ('CURRENCY_MISMATCH', 'Currency Mismatch'), ('CLASSIFICATION_MISMATCH', 'Classification Mismatch'), ('DATE_MISMATCH', 'Date Mismatch')], default='MATCHED', max_length=30)),
                ('source_amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('counterpart_amount', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-proposed_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('date_entered', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=1024)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('num', models.CharField(blank=True, db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('void', 'Void')], db_index=True, default='draft', max_length=20)),
                ('is_posted', models.BooleanField(db_index=True, default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('is_reversal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-date_entered'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=10, help_text="Quantity in account's commodity", max_digits=20)),
                ('value', models.DecimalField(decimal_places=10, help_text='Quantity in transaction currency', max_digits=20)),
                ('memo', models.CharField(blank=True, max_length=1024)),
                ('action', models.CharField(blank=True, max_length=50)),
                ('reconcile_status', models.CharField(choices=[('NOT_CLEARED', 'Not Cleared'), ('CLEARED', 'Cleared'), ('RECONCILED', 'Reconciled'), ('FROZEN', 'Frozen'), ('VOID', 'Void')], db_index=True, default='NOT_CLEARED', max_length=20)),
                ('date_reconciled', models.DateTimeField(blank=True, null=True)),
                ('online_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('voided_amount', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('voided_value', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_closed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('due_days', models.IntegerField()),
                ('discount_days', models.IntegerField(default=0)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationAuditLog',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('rule_type', models.CharField(choices=[('VALUE', 'Absolute Amount'), ('PERCENT', 'Percentage')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Tax rate (for PERCENT) or fixed amount (for VALUE)', max_digits=10)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='TransactionMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(default='pending', max_length=50)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('external_system', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
