# Generated by Django 5.2.17 on 2026-09-19 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('business_documents', '0001_initial'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='identity.legalentity'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='identity.legalentity'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='identity.legalentity'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='accounting.bankaccount'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_reconciliations', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='accounting.bankaccount'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='accounting.bankstatement'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.bankstatement'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounting.commodity'),
        ),
        migrations.AddField(
            model_name='account',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.commodity'),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.commodity',),
        ),
        migrations.AddField(
            model_name='counterpartposting',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='from_commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_rates', to='accounting.commodity'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='to_commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_rates', to='accounting.commodity'),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_periods', to='identity.legalentity'),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_periods', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='intercompanyrelationship',
            name='entity_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercompany_relationships_a', to='identity.legalentity'),
        ),
        migrations.AddField(
            model_name='intercompanyrelationship',
            name='entity_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercompany_relationships_b', to='identity.legalentity'),
        ),
        migrations.AddField(
            model_name='intercompanyrelationship',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercompany_relationships', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='interentityevent',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_intercompany_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interentityevent',
            name='counterparty_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparty_events', to='identity.legalentity'),
        ),
        migrations.AddField(
            model_name='interentityevent',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intercompany_events', to='accounting.commodity'),
        ),
        migrations.AddField(
            model_name='interentityevent',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_intercompany_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interentityevent',
            name='source_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_events', to='identity.legalentity'),
        ),
        migrations.AddField(
            model_name='interentityevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercompany_events', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='counterpartposting',
            name='inter_entity_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterpart_postings', to='accounting.interentityevent'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='correcting_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='identity.legalentity'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='business_documents.accountingdocument'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='transaction_currency',
            field=models.ForeignKey(help_text='The currency in which this journal balances', on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.commodity'),
        ),
        migrations.AddField(
            model_name='interentityevent',
            name='counterpart_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counterpart_events', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='interentityevent',
            name='source_journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_events', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='counterpartposting',
            name='proposed_journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterpart_postings', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='matched_journal_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='accounting.journalline'),
        ),
        migrations.AddField(
            model_name='lot',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='lot',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='business_documents.accountingdocument'),
        ),
        migrations.AddField(
            model_name='lot',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='identity.legalentity'),
        ),
        migrations.AddField(
            model_name='lot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='accounting.lot'),
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='reconciliationauditlog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationauditlog',
            name='journal_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_audit_log', to='accounting.journalline'),
        ),
        migrations.AddField(
            model_name='reconciliationauditlog',
            name='reconciliation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to='accounting.bankreconciliation'),
        ),
        migrations.AddField(
            model_name='taxrule',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_rules', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='taxrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='transactionmetadata',
            name='journal_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='transactionmetadata',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['tenant', 'timestamp'], name='accounting__tenant__fc6b68_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['entity_type', 'entity_id'], name='accounting__entity__b2d65a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action', 'timestamp'], name='accounting__action_9f4acc_idx'),
        ),
        migrations.AddIndex(
            model_name='commodity',
            index=models.Index(fields=['namespace', 'mnemonic'], name='accounting__namespa_c7451e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commodity',
            unique_together={('namespace', 'mnemonic', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('bank_name', 'account_number', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['code'], name='accounting__code_c93a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type'], name='accounting__account_889d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['path'], name='accounting__path_30c950_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tenant', 'legal_entity'], name='accounting__tenant__ee636e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name', 'parent', 'legal_entity')},
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['from_commodity', 'to_commodity', 'rate_date'], name='accounting__from_co_ea2af4_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['rate_date'], name='accounting__rate_da_6f7483_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('from_commodity', 'to_commodity', 'rate_date', 'source')},
        ),
        migrations.AddIndex(
            model_name='fiscalperiod',
            index=models.Index(fields=['tenant', 'legal_entity', 'status'], name='accounting__tenant__201efc_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalperiod',
            index=models.Index(fields=['start_date', 'end_date'], name='accounting__start_d_9f449b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalperiod',
            unique_together={('start_date', 'end_date', 'legal_entity')},
        ),
        migrations.AlterUniqueTogether(
            name='intercompanyrelationship',
            unique_together={('entity_a', 'entity_b', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='accounting__date_e3f521_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['status', 'date'], name='accounting__status_755796_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'legal_entity', 'date'], name='accounting__tenant__297372_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['is_posted'], name='accounting__is_post_95b69a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['idempotency_key'], name='accounting__idempot_075371_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['statement', 'transaction_date'], name='accounting__stateme_126632_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['online_id'], name='accounting__online__b4c069_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['account', 'is_closed'], name='accounting__account_c89b10_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['journal_entry'], name='accounting__journal_2bbae4_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account'], name='accounting__account_c6b1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['reconcile_status'], name='accounting__reconci_aee18a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['lot'], name='accounting__lot_id_b27ed1_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationauditlog',
            index=models.Index(fields=['journal_line', 'changed_at'], name='accounting__journal_667410_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationauditlog',
            index=models.Index(fields=['changed_by'], name='accounting__changed_f75615_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['code', 'effective_from'], name='accounting__code_661b00_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['tenant', 'is_active'], name='accounting__tenant__2e79e4_idx'),
        ),
    ]
