"""Acceptance tests for the Reporting & Analytics bounded context.

These tests encode the behavior-contract rules that the reporting
context must satisfy. Each test is tagged with a rule ID; the rule
IDs are derived from the architectural requirements in
``REIMAGINED_ARCHITECTURE.md`` Section 6 and Section 9.7.

NOTE: The AI_NATIVE_SPEC does not define explicit ``BR-RPT-xxx`` rules
for the reporting context (unlike ``BR-ACCT-xxx`` for the accounting
engine). The rule IDs below are derived from the architectural
requirements and are marked as ``@pytest.mark.acceptance`` so they
can be run independently.

The rules are:

* RPT-001: Reports are deterministic — same input → same output.
* RPT-002: Reports are tenant-scoped — no cross-tenant leakage.
* RPT-003: AI insights require evidence — no hallucinated insights.
* RPT-004: Report lifecycle state transitions are explicit.
* RPT-005: Async report generation with proper state management.
* RPT-006: AI explainer is never asked to perform arithmetic.
* RPT-007: Golden accounting tests must pass before reporting on posted data.
"""

from __future__ import annotations

import datetime as dt
import uuid
from decimal import Decimal
from pathlib import Path

import pytest
from django.test import override_settings

from reporting_analytics.exceptions import (
    EvidenceMissingError,
    ReportParametersInvalidError,
)
from reporting_analytics.middleware import tenant_scope
from reporting_analytics.models import (
    AnalyticInsight,
    AnalyticQuery,
    QueryKind,
    ReportDefinition,
    ReportInstance,
    ReportStatus,
    ReportType,
)
from reporting_analytics.services import (
    ai_explainer,
    analytics_engine,
    report_generator,
)
from reporting_analytics.services.analytics_engine import (
    AnalyticResult,
    EvidenceReference,
    Metric,
    require_evidence,
)
from reporting_analytics.services.report_generator import (
    ReportParameters,
    validate_parameters,
)


# ---------------------------------------------------------------------------
# RPT-001: Reports are deterministic
# ---------------------------------------------------------------------------


@pytest.mark.acceptance
@pytest.mark.rule("RPT-001")
def test_report_is_deterministic(tenant_id: str, today: dt.date):
    """Given the same definition + parameters + ledger state, the output
    is identical on every invocation.

    This test invokes the trial_balance generator twice with the same
    inputs and asserts the output is identical.
    """
    parameters = ReportParameters(
        date_from=dt.date(2026, 1, 1),
        date_to=today,
    )
    result_a = report_generator._trial_balance(
        tenant_id=tenant_id, parameters=parameters
    )
    result_b = report_generator._trial_balance(
        tenant_id=tenant_id, parameters=parameters
    )
    assert result_a.definition_code == result_b.definition_code
    assert result_a.parameters == result_b.parameters
    assert result_a.columns == result_b.columns
    assert result_a.rows == result_b.rows
    assert result_a.row_count == result_b.row_count


# ---------------------------------------------------------------------------
# RPT-002: Reports are tenant-scoped
# ---------------------------------------------------------------------------


@pytest.mark.acceptance
@pytest.mark.rule("RPT-002")
def test_report_is_tenant_scoped(tenant_id: str, today: dt.date):
    """A report query for tenant A must not include rows from tenant B.

    This test is a structural assertion: the SQL generated by the
    report generator includes a ``WHERE tenant_id = %(tenant_id)s``
    clause. We cannot test the actual isolation without a real
    Postgres with RLS policies loaded; that is covered by the
    integration test suite (marked ``@pytest.mark.rls``).
    """
    parameters = ReportParameters(
        date_from=dt.date(2026, 1, 1),
        date_to=today,
    )
    # The trial_balance SQL is a string; we assert it contains the
    # tenant filter.
    import inspect

    source = inspect.getsource(report_generator._trial_balance)
    assert "tenant_id = %(tenant_id)s" in source, (
        "trial_balance SQL must filter by tenant_id"
    )


# ---------------------------------------------------------------------------
# RPT-003: AI insights require evidence
# ---------------------------------------------------------------------------


@pytest.mark.acceptance
@pytest.mark.rule("RPT-003")
def test_insight_requires_evidence():
    """An AnalyticInsight must have at least one evidence reference.

    If the deterministic query produces no evidence, the insight must
    NOT be persisted — this prevents hallucinated insights.
    """
    query = AnalyticQuery(
        guid=uuid.uuid4(),
        tenant_id="tenant-test-0001",
        kind=QueryKind.ANOMALY,
        parameters={},
    )
    insight = AnalyticInsight(
        guid=uuid.uuid4(),
        tenant_id="tenant-test-0001",
        query=query,
        status="generated",
        evidence=[],  # Empty evidence — should fail.
        narrative="This is a hallucinated insight.",
    )
    with pytest.raises(ValueError, match="at least one evidence reference"):
        insight.save()


@pytest.mark.acceptance
@pytest.mark.rule("RPT-003")
def test_explainer_refuses_no_evidence():
    """The AI explainer must refuse to generate a narrative if the
    analytic result has no evidence.

    This is a safety check: the LLM must never be asked to explain
    nothing.
    """
    result = AnalyticResult(
        query_kind=QueryKind.ANOMALY,
        metrics=[Metric(name="outlier_count", value=0, unit="count", as_of=dt.date(2026, 9, 19))],
        evidence=[],  # Empty evidence.
    )
    with pytest.raises(EvidenceMissingError):
        ai_explainer.explain(result=result)


# ---------------------------------------------------------------------------
# RPT-004: Report lifecycle state transitions
# ---------------------------------------------------------------------------


@pytest.mark.acceptance
@pytest.mark.rule("RPT-004")
def test_report_lifecycle_transitions():
    """A ReportInstance must follow the allowed state transitions:

        pending → running → succeeded | failed
                  ↓
              cancelled (only from pending/running)
    """
    instance = ReportInstance(status=ReportStatus.PENDING)
    # Valid transitions.
    instance.transition_to(ReportStatus.RUNNING)
    assert instance.status == ReportStatus.RUNNING
    instance.transition_to(ReportStatus.SUCCEEDED)
    assert instance.status == ReportStatus.SUCCEEDED

    # Invalid transition: succeeded → pending.
    with pytest.raises(ValueError, match="cannot transition"):
        instance.transition_to(ReportStatus.PENDING)


@pytest.mark.acceptance
@pytest.mark.rule("RPT-004")
def test_report_can_be_cancelled_from_pending():
    """A pending report can be cancelled."""
    instance = ReportInstance(status=ReportStatus.PENDING)
    instance.transition_to(ReportStatus.CANCELLED)
    assert instance.status == ReportStatus.CANCELLED


@pytest.mark.acceptance
@pytest.mark.rule("RPT-004")
def test_report_cannot_be_cancelled_from_succeeded():
    """A succeeded report cannot be cancelled."""
    instance = ReportInstance(status=ReportStatus.SUCCEEDED)
    with pytest.raises(ValueError, match="cannot transition"):
        instance.transition_to(ReportStatus.CANCELLED)


# ---------------------------------------------------------------------------
# RPT-005: Async report generation
# ---------------------------------------------------------------------------


@pytest.mark.acceptance
@pytest.mark.rule("RPT-005")
def test_report_parameters_validation():
    """Report parameters must be validated before generation."""
    definition = ReportDefinition(
        guid=uuid.uuid4(),
        code="trial_balance",
        name="Trial Balance",
        report_type=ReportType.TRIAL_BALANCE,
        parameter_schema={},
        query_template="",
    )
    # Valid parameters.
    params = validate_parameters(
        definition,
        {"date_from": "2026-01-01", "date_to": "2026-09-19"},
    )
    assert params.date_from == dt.date(2026, 1, 1)
    assert params.date_to == dt.date(2026, 9, 19)

    # Invalid: date_from > date_to.
    with pytest.raises(ReportParametersInvalidError, match="date_from must not be after"):
        validate_parameters(
            definition,
            {"date_from": "2026-12-31", "date_to": "2026-01-01"},
        )


# ---------------------------------------------------------------------------
# RPT-006: AI explainer is never asked to perform arithmetic
# ---------------------------------------------------------------------------


@pytest.mark.acceptance
@pytest.mark.rule("RPT-006")
def test_explainer_prompt_does_not_ask_for_arithmetic():
    """The AI explainer's system prompt must instruct the LLM NOT to
    perform arithmetic.

    This is a structural assertion: we inspect the prompt template.
    """
    import inspect

    source = inspect.getsource(ai_explainer.OpenAIExplainer)
    assert "Do NOT perform arithmetic" in source, (
        "OpenAI explainer system prompt must instruct the LLM not to "
        "perform arithmetic"
    )


# ---------------------------------------------------------------------------
# RPT-007: Golden accounting tests dependency
# ---------------------------------------------------------------------------


@pytest.mark.acceptance
@pytest.mark.rule("RPT-007")
@pytest.mark.golden_dependency
def test_golden_dependency_gate(tmp_path: Path):
    """The reporting context depends on the accounting engine's golden
    tests passing before any report that touches posted data can be
    considered correct.

    This test verifies the dependency-gate mechanism: if the golden
    manifest is missing or stale, tests marked with
    ``@pytest.mark.golden_dependency`` are skipped.
    """
    manifest_path = tmp_path / "golden.lock"
    # Simulate a missing manifest.
    assert not manifest_path.exists()
    # The gate should skip the test.
    # (In practice, the pytest plugin would check this before running.)
    # Here we just assert the mechanism exists.
    from reporting_analytics.services import golden_dependency

    assert golden_dependency.is_golden_green(manifest_path) is False

    # Simulate a green manifest.
    manifest_path.write_text("status=green\ncommit=abc123\n")
    assert golden_dependency.is_golden_green(manifest_path) is True


# ---------------------------------------------------------------------------
# Additional: Analytic query runners
# ---------------------------------------------------------------------------


@pytest.mark.acceptance
@pytest.mark.rule("RPT-001")
def test_analytic_result_has_evidence_references():
    """Every AnalyticResult must carry evidence references."""
    result = AnalyticResult(
        query_kind=QueryKind.VARIANCE,
        metrics=[
            Metric(name="delta", value=Decimal("100"), unit="SGD", as_of=dt.date(2026, 9, 19))
        ],
        evidence=[
            EvidenceReference(
                kind="account",
                id="acc-001",
                description="Operating Expenses",
            )
        ],
    )
    assert len(result.evidence) == 1
    assert result.evidence[0].kind == "account"
    assert result.evidence[0].id == "acc-001"


@pytest.mark.acceptance
@pytest.mark.rule("RPT-003")
def test_require_evidence_raises_on_empty():
    """require_evidence raises if the result has no evidence."""
    result = AnalyticResult(
        query_kind=QueryKind.ANOMALY,
        metrics=[],
        evidence=[],
    )
    with pytest.raises(EvidenceMissingError):
        require_evidence(result)
