# Generated by Django 5.2.17 on 2026-09-19 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticQuery',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('variance', 'Variance analysis'), ('trend', 'Trend detection'), ('anomaly', 'Anomaly surfacing'), ('working_capital', 'Working-capital analysis'), ('cash_flow_forecast', 'Cash-flow forecast'), ('financial_ratio', 'Financial ratio'), ('custom', 'Custom analytic query')], max_length=32)),
                ('natural_language_question', models.TextField(blank=True, help_text='Free-form question from the user, if any.')),
                ('executed_query', models.TextField(blank=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytic_queries', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='analytic_queries', to='identity.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticInsight',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('evidence', models.JSONField(default=list)),
                ('narrative', models.TextField(blank=True)),
                ('llm_provider', models.CharField(blank=True, max_length=64)),
                ('llm_model', models.CharField(blank=True, max_length=128)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_insights', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='analytic_insights', to='identity.tenant')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='reporting.analyticquery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='A tenant may have at most one default dashboard.')),
                ('layout', models.JSONField(blank=True, default=list, help_text='Ordered list of widget placements (grid coordinates).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_dashboards', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='identity.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('balance_sheet', 'Balance Sheet'), ('income_statement', 'Income Statement'), ('cash_flow', 'Cash Flow Statement'), ('trial_balance', 'Trial Balance'), ('general_ledger', 'General Ledger'), ('aged_receivables', 'Aged Receivables'), ('aged_payables', 'Aged Payables'), ('custom', 'Custom / Ad-hoc')], max_length=32)),
                ('parameter_schema', models.JSONField(blank=True, default=dict)),
                ('query_template', models.TextField()),
                ('default_parameters', models.JSONField(blank=True, default=dict)),
                ('is_system', models.BooleanField(default=False, help_text='System reports cannot be deleted by tenants.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='report_definitions', to='identity.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_type', models.CharField(choices=[('report', 'Standard report'), ('kpi', 'Pre-built KPI'), ('chart', 'Chart (line, bar, pie, …)'), ('text', 'Static text / markdown')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('kpi_name', models.CharField(blank=True, max_length=128)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('visual_config', models.JSONField(blank=True, default=dict)),
                ('position', models.IntegerField(default=0)),
                ('cache_ttl_seconds', models.IntegerField(default=300)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reporting.dashboard')),
                ('report_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widgets', to='reporting.reportdefinition')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ReportInstance',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('executed_query', models.TextField(blank=True)),
                ('result_rows', models.JSONField(blank=True, default=list)),
                ('result_artifact_key', models.CharField(blank=True, max_length=512)),
                ('output_format', models.CharField(choices=[('json', 'JSON (structured rows)'), ('csv', 'CSV'), ('pdf', 'PDF'), ('xlsx', 'Excel')], default='json', max_length=8)),
                ('row_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='reporting.reportdefinition')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='report_instances', to='identity.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='analyticquery',
            index=models.Index(fields=['tenant', 'kind'], name='reporting_a_tenant__088ecf_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticquery',
            index=models.Index(fields=['tenant', 'created_at'], name='reporting_a_tenant__4e57e6_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticinsight',
            index=models.Index(fields=['tenant', 'status'], name='reporting_a_tenant__afd8be_idx'),
        ),
        migrations.AddConstraint(
            model_name='dashboard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant',), name='uq_dashboard_tenant_default'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['tenant', 'report_type'], name='reporting_r_tenant__93b9ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportdefinition',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_report_definition_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='reportinstance',
            index=models.Index(fields=['tenant', 'status'], name='reporting_r_tenant__47e64b_idx'),
        ),
        migrations.AddIndex(
            model_name='reportinstance',
            index=models.Index(fields=['tenant', 'created_at'], name='reporting_r_tenant__25b605_idx'),
        ),
    ]
