# Generated by Django 5.2.17 on 2026-09-19 11:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingMapping',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('legal_entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('supplier_party_id', models.UUIDField(blank=True, db_index=True, help_text="Match by supplier party. NULL means 'any supplier'.", null=True)),
                ('description_pattern', models.CharField(blank=True, help_text='Substring / regex matched against line descriptions.', max_length=255)),
                ('amount_range_min', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('amount_range_max', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('target_account_id', models.UUIDField(db_index=True)),
                ('target_tax_rule_id', models.UUIDField(blank=True, null=True)),
                ('target_dimension_id', models.UUIDField(blank=True, null=True)),
                ('confidence', models.CharField(choices=[('high', 'High — auto-apply'), ('medium', 'Medium — suggest with confirmation'), ('low', 'Low — always require review')], default='medium', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('retired_by', models.UUIDField(blank=True, null=True)),
                ('retirement_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounting_mappings',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['tenant_id', 'supplier_party_id'], name='accounting__tenant__59a9ed_idx'), models.Index(fields=['tenant_id', 'is_active'], name='accounting__tenant__778208_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('legal_entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('original_file_key', models.CharField(help_text='S3 object key of the original uploaded file. IMMUTABLE.', max_length=512)),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 of the original uploaded file. IMMUTABLE.', max_length=64)),
                ('mime_type', models.CharField(max_length=128)),
                ('original_filename', models.CharField(max_length=512)),
                ('size_bytes', models.BigIntegerField()),
                ('source', models.CharField(choices=[('web_upload', 'Web upload (drag-drop)'), ('email', 'Email inbound'), ('api', 'External API'), ('mobile', 'Mobile app'), ('bank_feed', 'Bank statement feed')], default='web_upload', max_length=32)),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('uploaded_by', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded (awaiting extraction)'), ('extracting', 'OCR/extraction in progress'), ('extracted', 'Extraction complete (pending match)'), ('matching', 'Matching in progress'), ('matched', 'Matched to party / accounting document'), ('in_review', 'Awaiting human review'), ('approved', 'Human-approved (ready for posting)'), ('posted', 'Downstream accounting document posted'), ('rejected', 'Rejected during review'), ('archived', 'Archived (no action pending)')], db_index=True, default='uploaded', max_length=32)),
                ('is_duplicate', models.BooleanField(db_index=True, default=False)),
                ('resulting_accounting_document_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_copies', to='document_intelligence.document')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentExtraction',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(help_text='Strictly monotonic within a document.')),
                ('ocr_provider', models.CharField(help_text='e.g. aws_textract, google_document_ai, mock', max_length=50)),
                ('ocr_model_version', models.CharField(max_length=100)),
                ('extraction_model_version', models.CharField(max_length=100)),
                ('extraction_result', models.JSONField(default=dict, help_text='Structured extraction output: supplier, customer, dates, amounts, line items, tax, invoice number, etc.')),
                ('ai_suggestion', models.JSONField(blank=True, help_text='JSON object with suggested account/tax/dimension/party plus the evidence trail (which historical mapping, which exemplars).', null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, help_text='0.0000 – 1.0000', max_digits=5, null=True)),
                ('confidence_evidence', models.JSONField(blank=True, help_text='Provenance of the confidence score (exemplar IDs, weights).', null=True)),
                ('is_human_correction', models.BooleanField(default=False)),
                ('human_correction', models.JSONField(blank=True, help_text='Optional structured corrections submitted by the reviewer.', null=True)),
                ('correction_note', models.TextField(blank=True)),
                ('reviewed_by', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued for OCR'), ('ocr_in_progress', 'OCR in progress'), ('ocr_failed', 'OCR failed'), ('extraction_in_progress', 'Extraction in progress'), ('extraction_failed', 'Extraction failed'), ('completed', 'Completed (structured result)'), ('rejected', 'Rejected during human review')], db_index=True, default='queued', max_length=32)),
                ('resulting_accounting_document_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_mapping_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions', to='document_intelligence.accountingmapping')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='document_intelligence.document')),
            ],
            options={
                'db_table': 'document_extractions',
                'ordering': ['document', 'version'],
            },
        ),
        migrations.CreateModel(
            name='DocumentMatch',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('party', 'Matched to a Party (supplier / customer)'), ('accounting_document', 'Matched to an existing AccountingDocument'), ('bank_transaction', 'Matched to a BankTransaction'), ('duplicate', 'Identified as duplicate of another Document')], max_length=32)),
                ('status', models.CharField(choices=[('proposed', 'Proposed by the matching pipeline'), ('accepted', 'Accepted (manually or automatically)'), ('rejected', 'Explicitly rejected by reviewer'), ('superseded', 'Superseded by a later match')], db_index=True, default='proposed', max_length=32)),
                ('target_party_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('target_accounting_document_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('target_bank_transaction_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('target_document_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('evidence', models.JSONField(default=dict)),
                ('decided_by', models.UUIDField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='document_intelligence.document')),
                ('extraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='document_intelligence.documentextraction')),
            ],
            options={
                'db_table': 'document_matches',
                'ordering': ['-confidence', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_version', models.IntegerField(default=0)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='version_counter', to='document_intelligence.document')),
            ],
            options={
                'db_table': 'document_extraction_versions',
            },
        ),
        migrations.CreateModel(
            name='MappingSuggestion',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('suggested_account_id', models.UUIDField(blank=True, db_index=True, help_text='Suggested target account for the journal entry.', null=True)),
                ('suggested_tax_rule_id', models.UUIDField(blank=True, help_text='Suggested tax rule.', null=True)),
                ('suggested_dimension_id', models.UUIDField(blank=True, help_text='Suggested dimension (e.g., department, project).', null=True)),
                ('suggested_party_id', models.UUIDField(blank=True, db_index=True, help_text='Suggested party (supplier or customer).', null=True)),
                ('source_mapping_ids', models.JSONField(default=list, help_text='List of AccountingMapping.guid that contributed to this suggestion.')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, help_text='0.0000 – 1.0000. Used for review routing (BR-DI-006).', max_digits=5, null=True)),
                ('evidence', models.JSONField(default=dict, help_text='Provenance trail: exemplar IDs, weights, which mappings matched.')),
                ('llm_provider', models.CharField(blank=True, help_text="e.g. openai, anthropic, or 'rule_based' if no LLM used.", max_length=50)),
                ('llm_model_version', models.CharField(blank=True, help_text='Model version used for suggestion.', max_length=100)),
                ('accepted', models.BooleanField(db_index=True, default=False, help_text='True if human accepted this suggestion.')),
                ('rejected', models.BooleanField(default=False, help_text='True if human rejected this suggestion.')),
                ('decided_by', models.UUIDField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_suggestions', to='document_intelligence.documentextraction')),
            ],
            options={
                'db_table': 'mapping_suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewQueue',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned to reviewer'), ('approved', 'Approved by reviewer'), ('corrected', 'Corrected by reviewer (creates extraction v+1)'), ('rejected', 'Rejected (no downstream action)'), ('cancelled', 'Cancelled (e.g. document deleted)')], db_index=True, default='open', max_length=32)),
                ('priority', models.IntegerField(db_index=True, default=0, help_text='Higher = more urgent. Derived from confidence gap.')),
                ('reason', models.CharField(blank=True, help_text="Why this item needs review (e.g. 'low_confidence', 'duplicate').", max_length=255)),
                ('assigned_to', models.UUIDField(blank=True, db_index=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.UUIDField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='document_intelligence.document')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='document_intelligence.documentextraction')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_items', to='document_intelligence.mappingsuggestion')),
            ],
            options={
                'db_table': 'review_queue',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDecisionLog',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('decision', models.CharField(choices=[('approve_as_is', 'Approve extraction without changes'), ('correct_and_approve', 'Correct extraction then approve'), ('reject_no_action', 'Reject with no downstream action'), ('request_more_info', 'Request additional information'), ('escalate', 'Escalate to senior reviewer')], help_text='The specific decision made.', max_length=32)),
                ('decision_note', models.TextField(blank=True, help_text='Optional note explaining the decision.')),
                ('correction_data', models.JSONField(blank=True, help_text='If decision is CORRECT_AND_APPROVE, the correction payload.', null=True)),
                ('decided_by', models.UUIDField(db_index=True)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_log', to='document_intelligence.reviewqueue')),
            ],
            options={
                'db_table': 'review_decision_log',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant_id', 'content_hash'], name='documents_tenant__512caf_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant_id', 'status'], name='documents_tenant__ebc015_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentextraction',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='uniq_extraction_per_document_version'),
        ),
        migrations.AddConstraint(
            model_name='documentmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('document', 'kind'), name='uniq_accepted_match_per_document_kind'),
        ),
        migrations.AddIndex(
            model_name='mappingsuggestion',
            index=models.Index(fields=['tenant_id', 'accepted'], name='mapping_sug_tenant__2c9acb_idx'),
        ),
        migrations.AddIndex(
            model_name='mappingsuggestion',
            index=models.Index(fields=['extraction', 'confidence_score'], name='mapping_sug_extract_ed0ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewqueue',
            index=models.Index(fields=['tenant_id', 'status'], name='review_queu_tenant__2d1b02_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewqueue',
            index=models.Index(fields=['assigned_to', 'status'], name='review_queu_assigne_c081b8_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewdecisionlog',
            index=models.Index(fields=['tenant_id', 'decided_at'], name='review_deci_tenant__ba32a5_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewdecisionlog',
            index=models.Index(fields=['review_item', 'decision'], name='review_deci_review__c877d8_idx'),
        ),
    ]
