# Generated by Django 5.2.17 on 2026-09-19 11:00

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingDocument',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('reference_number', models.CharField(blank=True, help_text='External reference', max_length=100)),
                ('document_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('BILL', 'Bill'), ('CREDIT_NOTE', 'Credit Note')], max_length=20)),
                ('direction', models.CharField(choices=[('SALES', 'Sales'), ('PURCHASE', 'Purchase')], max_length=10)),
                ('document_date', models.DateField(help_text='Date on the document')),
                ('due_date', models.DateField(blank=True, help_text='Payment due date', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Sum of line items before tax', max_digits=20)),
                ('tax_total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Total tax amount', max_digits=20)),
                ('discount_total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Total discount amount', max_digits=20)),
                ('total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Total amount including tax and discount', max_digits=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True, help_text='Terms and conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic concurrency version')),
            ],
            options={
                'verbose_name': 'Accounting Document',
                'verbose_name_plural': 'Accounting Documents',
                'db_table': 'business_documents_accounting_document',
                'ordering': ['-document_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('step_order', models.PositiveIntegerField(help_text='Order of execution')),
                ('approver_role', models.CharField(blank=True, help_text="Role required to approve (e.g., 'APPROVER', 'MANAGER')", max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Approval Step',
                'verbose_name_plural': 'Approval Steps',
                'db_table': 'business_documents_approval_step',
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('applies_to_document_types', models.JSONField(default=list, help_text='List of DocumentType values this workflow applies to')),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=4, help_text='Minimum amount requiring approval', max_digits=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Approval Workflow',
                'verbose_name_plural': 'Approval Workflows',
                'db_table': 'business_documents_approval_workflow',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField(help_text='File size in bytes')),
                ('storage_key', models.CharField(help_text='S3 key or object storage path', max_length=500)),
                ('content_hash', models.CharField(help_text='SHA-256 hash of file content', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Attachment',
                'verbose_name_plural': 'Document Attachments',
                'db_table': 'business_documents_document_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('tax_included', models.BooleanField(default=False, help_text='Whether the unit price includes tax')),
                ('discount_ordering_mode', models.PositiveSmallIntegerField(choices=[(1, 'Pre-Tax'), (2, 'Same Time'), (3, 'Post-Tax')], default=1, help_text='How discount interacts with tax calculation')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, null=True)),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='quantity × unit_price', max_digits=20)),
                ('discount_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Calculated discount amount', max_digits=20)),
                ('tax_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Calculated tax amount', max_digits=20)),
                ('total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Final line total', max_digits=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Line',
                'verbose_name_plural': 'Document Lines',
                'db_table': 'business_documents_document_line',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('roles', models.JSONField(default=list, help_text='List of PartyRole values')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('address', models.JSONField(blank=True, default=dict, help_text='Structured address object')),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'db_table': 'business_documents_party',
                'ordering': ['name'],
            },
        ),
    ]
