# Generated by Django 5.2.17 on 2026-09-19 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('business_documents', '0001_initial'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_documents', to='identity.legalentity'),
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounting.paymentterm'),
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_documents', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='approver_user',
            field=models.ForeignKey(blank=True, help_text='Specific user approver (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='business_documents.accountingdocument'),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='business_documents.approvalworkflow'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='business_documents.accountingdocument'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentline',
            name='account',
            field=models.ForeignKey(help_text='Income/expense account for this line', on_delete=django.db.models.deletion.PROTECT, related_name='document_lines', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='business_documents.accountingdocument'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='tax_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_lines', to='accounting.taxrule'),
        ),
        migrations.AddField(
            model_name='party',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='party',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='accounting.paymentterm'),
        ),
        migrations.AddField(
            model_name='party',
            name='tax_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='accounting.taxrule'),
        ),
        migrations.AddField(
            model_name='party',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='identity.tenant'),
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_documents', to='business_documents.party'),
        ),
        migrations.AlterUniqueTogether(
            name='documentline',
            unique_together={('document', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['tenant', 'name'], name='business_do_tenant__d15182_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['tenant', 'email'], name='business_do_tenant__cbcf2a_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['is_active'], name='business_do_is_acti_a16c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingdocument',
            index=models.Index(fields=['tenant', 'status'], name='business_do_tenant__d0c9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingdocument',
            index=models.Index(fields=['tenant', 'party'], name='business_do_tenant__e473c7_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingdocument',
            index=models.Index(fields=['tenant', 'document_date'], name='business_do_tenant__99d1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingdocument',
            index=models.Index(fields=['tenant', 'document_type'], name='business_do_tenant__09ab8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountingdocument',
            unique_together={('tenant', 'document_number')},
        ),
    ]
