# Generated by Django 5.2.17 on 2026-09-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_adr010_posted_immutability'),
        ('business_documents', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documentline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='documentline_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='documentline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='documentline_unit_price_non_negative'),
        ),
    ]
